[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_launchpad = "FjP1QmctbWVKr6SuDRqFHw56aTNdpZXK42mGGsZne3wK"
anchor_lock_token = "FjP1QmctbWVKr6SuDRqFHw56aTNdpZXK42mGGsZne3wK"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/buitoan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
